---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
    - pip-compile-upgrade
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: >
          venv/
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell readme.md code.py
        language: python
        types: [text]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.16.1
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-2020>=1.6.0
          # - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
          - flake8-pytest-style>=1.2.2
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.3.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
