#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansibe_env.PWD.endswith('/ansbible')

- hosts: localhost
  connection: local
  roles:
  - matjah_mac