---
- name: Update Homebrew
  homebrew:
    name: git
    state: present
    update_homebrew: true
  tags:
    - brew

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
    upgrade_all: "{{ upgrade_homebrew_packages }}"
  with_items: "{{ homebrew_packages }}"
  when: homebrew_check.stat.exists
  tags:
    - brew

- name: Install Homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"
  when: homebrew_check.stat.exists
  tags:
    - brew

- name: Upgrade PyEnv
  ansible.builtin.command: brew unlink pyenv && brew install --head --fetch-head pyenv && brew link pyenv --head
  when:
    - not homebrew_check.stat.exists
    - not install_homebrew_if_missing
  tags:
    - pyenv
