---
- name: dotfiles dirs
  ansible.builtin.file:
    path: ~/.{{ item }}
    state: directory
    mode: "0755"
  loop:
    - config
    - zshrcd
  tags:
    - dotfiles

- name: dotfiles symlink
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/matjah_mac/files/dotfiles/{{ item }}"
    path: ~/.{{ item }}
    state: link
    mode: "0755"
  loop:
    - ansible.cfg
    - gitconfig
    - gitignore_global
    - zshrc
    - ssh/config
  tags:
    - dotfiles
