name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .pre-commit
          key: ${{ runner.os }}-pre-commit
      - uses: actions/setup-python@v3
        with:
          cache: pip
      - uses: pre-commit/action@v3.0.0
